version: "3.1"
services:
  certbot-dns-google:
    build:
      context: ./files
    image: ghcr.io/nakanod/certbot-dns-google:1.19.0
    env_file:
      - ./.env
    volumes:
      - ./config:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
      - ./work:/var/lib/letsencrypt
    secrets:
      - google-credentials-file

secrets:
  google-credentials-file:
    file: ./google-credentials-file
